*variables: whatever
*Do Abs together why not, should be fine
*Amp
ranksum area if(ab=="amp" & (spp=="E" | spp=="S")), by(spp)
ranksum area if(ab=="amp" & (spp=="E" | spp=="M")), by(spp)
ranksum area if(ab=="amp" & (spp=="E" | spp=="coop")), by(spp)
ranksum area if(ab=="amp" & (spp=="E" | spp=="comp")), by(spp)
ranksum area if(ab=="amp" & (spp=="E" | spp=="ES")), by(spp)
ranksum area if(ab=="amp" & (spp=="S" | spp=="M")), by(spp)
ranksum area if(ab=="amp" & (spp=="S" | spp=="coop")), by(spp)
ranksum area if(ab=="amp" & (spp=="S" | spp=="comp")), by(spp)
ranksum area if(ab=="amp" & (spp=="S" | spp=="ES")), by(spp)
ranksum area if(ab=="amp" & (spp=="M" | spp=="coop")), by(spp)
ranksum area if(ab=="amp" & (spp=="M" | spp=="comp")), by(spp)
ranksum area if(ab=="amp" & (spp=="M" | spp=="ES")), by(spp)
ranksum area if(ab=="amp" & (spp=="coop" | spp=="comp")), by(spp)
ranksum area if(ab=="amp" & (spp=="coop" | spp=="ES")), by(spp)
ranksum area if(ab=="amp" & (spp=="comp" | spp=="ES")), by(spp)
*Tet
ranksum area if(ab=="tet" & (spp=="E" | spp=="S")), by(spp)
ranksum area if(ab=="tet" & (spp=="E" | spp=="M")), by(spp)
ranksum area if(ab=="tet" & (spp=="E" | spp=="coop")), by(spp)
ranksum area if(ab=="tet" & (spp=="E" | spp=="comp")), by(spp)
ranksum area if(ab=="tet" & (spp=="S" | spp=="M")), by(spp)
ranksum area if(ab=="tet" & (spp=="S" | spp=="coop")), by(spp)
ranksum area if(ab=="tet" & (spp=="S" | spp=="comp")), by(spp)
ranksum area if(ab=="tet" & (spp=="M" | spp=="coop")), by(spp)
ranksum area if(ab=="tet" & (spp=="M" | spp=="comp")), by(spp)
ranksum area if(ab=="tet" & (spp=="coop" | spp=="comp")), by(spp)

