*Tet
ranksum area if(ab=="tet" & (spp=="E" | spp=="S")), by(spp)
ranksum area if(ab=="tet" & (spp=="E" | spp=="M")), by(spp)
ranksum area if(ab=="tet" & (spp=="E" | spp=="coop")), by(spp)
ranksum area if(ab=="tet" & (spp=="E" | spp=="comp")), by(spp)
ranksum area if(ab=="tet" & (spp=="S" | spp=="M")), by(spp)
ranksum area if(ab=="tet" & (spp=="S" | spp=="coop")), by(spp)
ranksum area if(ab=="tet" & (spp=="S" | spp=="comp")), by(spp)
ranksum area if(ab=="tet" & (spp=="M" | spp=="coop")), by(spp)
ranksum area if(ab=="tet" & (spp=="M" | spp=="comp")), by(spp)
ranksum area if(ab=="tet" & (spp=="coop" | spp=="comp")), by(spp)
